contacts/apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import logout

from contacts.apps.accounts.views import LoginPage, SettingsPage, ChangePasswordView, RegisterFormView

urlpatterns = [
    url(r'^login/$', LoginPage.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^settings/$', SettingsPage.as_view(), name='settings'),
    url(r'^change_password/$', ChangePasswordView.as_view(),name='change_password'),
]

contacts/apps/core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from contacts.apps.core.views import AllContacts,  GetAllContacts, DeleteContact, AddContact, AjaxContactChangeModal,\
    GetAllUser, AllUsers, AddContactCsv, Vero

urlpatterns = [
    url(r'^$', AllContacts.as_view(), name='all_contacts'),
    url(r'^ajax_get_all_contacts/$', GetAllContacts.as_view(), name='ajax_get_all_contacts'),
    url(r'^all_users/$', AllUsers.as_view(), name='all_users'),
    url(r'^ajax_clients_datatable/$', GetAllUser.as_view(), name='ajax_clients_datatable'),
    url(r'^ajax_contact_change_modal/$', AjaxContactChangeModal.as_view(), name='ajax_contact_change_modal'),
    url(r'^ajax_delete_contact_modal/$', DeleteContact.as_view(), name='ajax_delete_contact_modal'),
    url(r'^ajax_add_contact_modal/$', AddContact.as_view(), name='ajax_add_contact_modal'),
    url(r'^upload_csv_file/$', AddContactCsv.as_view(), name='upload_csv_file'),
    url(r'^ajax_add_contact_vero/$', Vero.as_view(), name='ajax_add_contact_vero'),

]

contacts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    # admin view
    url(r'^admin/', admin.site.urls),
    # accounts
    url(r'^', include('contacts.apps.accounts.urls', namespace="accounts")),
    # core
    url(r'^', include('contacts.apps.core.urls', namespace="core")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

contacts/apps/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    def __init__(self, *args, **kwargs):
        super(UserProfile, self).__init__(*args, **kwargs)

    user = models.OneToOneField(User, related_name='profile')
    phone_number = models.CharField(max_length=15)
    vero_api_key = models.CharField(max_length=109)

    def __unicode__(self):
        return self.user.username

contacts/apps/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from contacts.apps.accounts.models import UserProfile
from datetime import datetime


# Create your models here.
class Contacts(models.Model):
    user_profile = models.ForeignKey(UserProfile)
    contact_name = models.CharField(max_length=30, blank=False)
    contact_surname = models.CharField(max_length=30, blank=False)
    city_name = models.CharField(max_length=30, blank=True)
    country_name = models.CharField(max_length=30, blank=True)
    phone_number = models.CharField(max_length=15, blank=False)
    email_contact = models.EmailField(blank=False)
    date_birthday = models.DateField(null=False, blank=True)
    date_add = models.DateField(default=datetime.now())

contacts/apps/accounts/forms.py
import re
from django import forms
import requests
from contacts.apps.accounts.models import UserProfile
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth import authenticate


class SettingsForm(ModelForm):
    class Meta:
        model = User
        fields = ['username',  'first_name', 'last_name', 'email']

    def clean(self):
        form_data = super(SettingsForm, self).clean()
        if not self.is_valid():
            return form_data
        return form_data


class SettingsProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone_number', 'vero_api_key']

    def __init__(self, *args, **kwargs):
        super(SettingsProfileForm, self).__init__(*args, **kwargs)



class ChangePasswordForm(ModelForm):
    class Meta:
        model = User
        fields = []

    old_password = forms.CharField(required=True)
    new_password = forms.CharField(required=True)
    password_confirmation = forms.CharField(required=True)

    def clean(self):
        form_data = self.cleaned_data
        if not 'old_password' in form_data or not 'new_password' in form_data \
                or not 'password_confirmation' in form_data:
            self._errors['old_password'] = self.error_class(['Field is required'])
            self._errors['new_password'] = self.error_class(['Field is required'])
            self._errors['password_confirmation'] = self.error_class(['Field is required'])
            return form_data
        user = authenticate(username=self.instance.username, password=form_data['old_password'])
        if user is None:
            self._errors['old_password'] = self.error_class(['Wrong password'])
        if form_data['new_password'] != form_data['password_confirmation']:
            self._errors['new_password'] = self.error_class(['Passwords don\'t match'])
            self._errors['password_confirmation'] = self.error_class(['Passwords don\'t match'])
        if not re.match(r'[A-Za-z0-9@#$%^&+=]{8,32}', form_data['new_password']):
            self._errors['new_password'] = self.error_class(['Password must contain uppercase and lowercase '
                                                             'letters and has at least eight (8) characters '
                                                             'but no more than thirty two (32) characters.'])
        return form_data


class SignupUserForm(ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
        form_data = super(SignupUserForm, self).clean()
        no_required_data = False
        if not self.is_valid():
            no_required_data = True
        if User.objects.filter(username=form_data['username']):
            self._errors['username'] = self.error_class(['User with this username already exists.'])
            no_required_data = True
        if User.objects.filter(email=form_data['email']):
            self._errors['email'] = self.error_class(['User with this email already exists.'])
            no_required_data = True
        if self.cleaned_data['password'] != self.cleaned_data['password2']:
            self._errors['password'] = self.error_class(['Passwords don\'t match'])
            self._errors['password2'] = self.error_class(['Passwords don\'t match'])
            no_required_data = True
        if not re.match(r'[A-Za-z0-9@#$%^&+=]{8,32}', self.cleaned_data['password']):
            self._errors['password'] = self.error_class(['Password must contain uppercase and lowercase '
                                                          'letters and has at least eight (8) characters '
                                                          'but no more than thirty two (32) characters.'])
            no_required_data = True
        if no_required_data == True:
            return form_data


class SignupUserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone_number', 'vero_api_key']

    def __init__(self, *args, **kwargs):

        super(SignupUserProfileForm, self).__init__(*args, **kwargs)
    def __str__(self):

        return 'Profile for user {}'.format(self.user.username)

    def clean(self):
        form_data = super(SignupUserProfileForm, self).clean()
        if self.cleaned_data.get('vero_api_key', None):
            r = requests.request('POST', 'https://api.getvero.com/api/v2/users/track',
                             json={'auth_token': form_data['vero_api_key'], 'id': 'test', 'email': '',
                                   })
            if r.status_code == 401:
                self._errors['vero_api_key'] = self.error_class(['Your credentials are invalid!!!'])
                return form_data

contacts/apps/core/forms.py
from django import forms
from django.forms import ModelForm
from contacts.apps.core.models import Contacts


class ContactAddForm(ModelForm):
    class Meta:
        model = Contacts
        fields = ['id', 'contact_name', 'contact_surname', 'city_name', 'country_name',
                  'phone_number', 'email_contact', 'date_birthday', 'date_add']

    def clean(self):
        form_data = self.cleaned_data
        return form_data

contacts/apps/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
import json
import logging
import traceback
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseServerError, HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import FormView
from contacts.apps.accounts.forms import SettingsForm, SettingsProfileForm, ChangePasswordForm, \
    SignupUserForm, SignupUserProfileForm

from contacts.apps.accounts.models import UserProfile

logger = logging.getLogger('contacts')


class LoginPage(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('core:all_contacts'))
        return render(request, self.template_name, {'error': False})

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        logger.debug('Authenticating user %s with password: %s' % (username, password))
        if User.objects.filter(email=username):
            username = User.objects.get(email=username).username
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('core:all_contacts'))
        else:
            logger.debug('User not authenticated. Wrong login(%s)/password(%s).' % (request.POST['username'],
                                                                                    request.POST['password']))
            return render(request, self.template_name, {'error': True,
                                                        'message': 'User not authenticated. Wrong login/password'})


@method_decorator(login_required, name='dispatch')
class SettingsPage(View):
    template_name = 'settings.html'

    def get(self, request, *args, **kwargs):
        try:
            form = SettingsForm(instance=request.user)
            form_profile = SettingsProfileForm(instance=request.user.profile)
        except Exception as e:
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
        else:
            return render(request, self.template_name, {'form': form,
                                                        'form_profile': form_profile,
                                                        'updated': False})

    def post(self, request, *args, **kwargs):
        try:
            updated = False
            form = SettingsForm(request.POST, instance=request.user)
            form_profile = SettingsProfileForm(request.POST, instance=request.user.profile)
            if form.is_valid() and form_profile.is_valid():
                form.save()
                form_profile.save()
                updated = True
        except Exception as e:
            print e
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
            return HttpResponseServerError()
        else:
            return render(request, self.template_name, {'form': form,
                                                        'form_profile': form_profile,
                                                        'updated': updated})


class ChangePasswordView(View):
    template_name = 'change_password_form.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        try:
            data = {}
        except Exception as e:
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
        else:
            return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        try:
            form = ChangePasswordForm(request.POST, instance=request.user)
            if form.is_valid():
                user = request.user
                user.set_password(form.cleaned_data['new_password'])
                user.save()
                return HttpResponse(json.dumps({'success': True}),
                                    content_type='application/json')
            else:
                return HttpResponse(json.dumps({'success': False,
                                                'errors': [(k, v[0]) for k, v in form.errors.items()]}),
                                    content_type='application/json')
        except Exception as e:
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))


class RegisterFormView(FormView):
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        form = SignupUserForm()
        form_profile = SignupUserProfileForm()
        context = {'form': form,
                   'form_profile': form_profile}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        updated = False
        try:
            form = SignupUserForm(request.POST)
            form_profile = SignupUserProfileForm(request.POST)
            if form.is_valid() and form_profile.is_valid():
                # Create a new user object but avoid saving it yet
                new_user = form.save(commit=False)
                # Set the chosen password
                new_user.set_password(form.cleaned_data['password'])
                # Save the User object
                new_user.save()
                user_profile = form_profile.save(commit=False)
                user_profile.user = new_user
                user_profile.save()
                updated = True
                template_name1 = 'login.html'
                return render(request, template_name1, {'updated': updated,})
                # return HttpResponseRedirect(reverse('accounts:login'))
        except Exception as e:
            print e
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
        else:
            return render(request, self.template_name, {'form': form,
                                                        'form_profile':form_profile})

contacts/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/AdminLTE.min.css" %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="{% static "dist/css/skins/skin-yellow-light.min.css" %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="{% static "plugins/jQuery/jQuery-2.1.4.min.js" %}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static "dist/js/app.min.js" %}"></script>

    <!-- Optionally, you can add Slimscroll and FastClick plugins.
         Both of these plugins are recommended to enhance the
         user experience. Slimscroll is required when using the
         fixed layout. -->

    <link href="{% static "plugins/iCheck/flat/orange.css" %}" rel="stylesheet">
    <script src="{% static "plugins/iCheck/icheck.js" %}"></script>
    {% block header %}
    {% endblock %}
</head>
<body class="hold-transition skin-blue-light sidebar-mini sidebar-collapse">
<div class="wrapper">
    <!-- Main Header -->
    <header class="main-header">
        <!-- Logo -->
        <a href="" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b><i class="fa fa-circle-o"></i></b>Countacts</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b></b>Countacts</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <span class="hidden-xs"></span>

                </ul>
                <ul class="nav navbar-nav">
                     <!-- User Account Menu -->
                  <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="hidden-xs">{{ user }}</span>
                            <i class="fa fa-user"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-footer">
                                <div class="pull-left">
                                   <a href="{% url "accounts:settings" %}" class="btn btn-default btn-flat">Settings</a>
                                </div>

                                <div class="pull-right">
                                    <a href="{% url "accounts:logout" %}" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    {% if user.is_superuser %}
    {% include "sidebar_menu_admin.html" %}
    {% else %}
    {% include "sidebar_menu_client.html" %}
    {% endif %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block content_wrapper %}
        {% endblock %}
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->

</div>
<!-- ./wrapper -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/bootbox/bootbox.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.file-input.js' %}"></script>
.
<script>
     var links = {
         get_all_contacts: "{% url 'core:ajax_get_all_contacts' %}",
         ajax_clients_datatable: "{% url 'core:ajax_clients_datatable' %}",
         ajax_contact_change_modal: "{% url 'core:ajax_contact_change_modal' %}",
         ajax_delete_contact_modal: "{% url 'core:ajax_delete_contact_modal' %}",
         ajax_add_contact_modal: "{% url 'core:ajax_add_contact_modal' %}",
         upload_csv_file: "{% url 'core:upload_csv_file' %}",
         ajax_add_contact_vero: "{% url 'core:ajax_add_contact_vero' %}",
         ajax_change_password_form: '{% url "accounts:change_password" %}',
     }
</script>
<script src="{% static "js/general.js" %}"></script>
{% block js_bottom %}
{% endblock %}
</body>
</html>

contacts/templates/base_auth.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Contacts | Log In</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
{% block body %}

{% endblock %}
{% block js_bottom %}
{% endblock %}
</html>

contacts/templates/sidebar_menu_admin.html
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li id="menu_contacts"><a href="{% url 'core:all_contacts' %}"><i class="fa fa-bar-chart"></i> <span>All Contacts</span></a></li>
            <li id="menu_clients"><a href="{% url 'core:all_users' %}"><i class="fa fa-users"></i> <span>Manage Clients</span></a></li>
            <li class="header">Settings</li>
            <li id="menu_settings"><a href="{% url "accounts:settings" %}"><i class="fa fa-gear"></i> <span>My settings</span></a></li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

contacts/templates/sidebar_menu_client.html
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li id="menu_contacts"><a href="{% url "core:all_contacts"%}"><i class="fa fa-bar-chart"></i> <span>All Contacts</span></a></li>
            <li class="header">Settings</li>
            <li id="menu_settings"><a href="{% url "accounts:settings" %}"><i class="fa fa-gear"></i> <span>My settings</span></a></li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>