contacts/apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.views import logout

from contacts.apps.accounts.views import LoginPage, SettingsPage, ChangePasswordView, RegisterFormView

urlpatterns = [
    url(r'^login/$', LoginPage.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^settings/$', SettingsPage.as_view(), name='settings'),
    url(r'^change_password/$', ChangePasswordView.as_view(),name='change_password'),
]

contacts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    # admin view
    url(r'^admin/', admin.site.urls),
    # accounts
    url(r'^', include('contacts.apps.accounts.urls', namespace="accounts")),
    # core
    url(r'^', include('contacts.apps.core.urls', namespace="core")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

contacts/apps/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    def __init__(self, *args, **kwargs):
        super(UserProfile, self).__init__(*args, **kwargs)

    user = models.OneToOneField(User, related_name='profile')
    phone_number = models.CharField(max_length=15)
    vero_api_key = models.CharField(max_length=109)

    def __unicode__(self):
        return self.user.username

contacts/apps/accounts/forms.py
import re
from django import forms
import requests
from contacts.apps.accounts.models import UserProfile
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth import authenticate


class SettingsForm(ModelForm):
    class Meta:
        model = User
        fields = ['username',  'first_name', 'last_name', 'email']

    def clean(self):
        form_data = super(SettingsForm, self).clean()
        if not self.is_valid():
            return form_data
        return form_data


class SettingsProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone_number', 'vero_api_key']

    def __init__(self, *args, **kwargs):
        super(SettingsProfileForm, self).__init__(*args, **kwargs)



class ChangePasswordForm(ModelForm):
    class Meta:
        model = User
        fields = []

    old_password = forms.CharField(required=True)
    new_password = forms.CharField(required=True)
    password_confirmation = forms.CharField(required=True)

    def clean(self):
        form_data = self.cleaned_data
        if not 'old_password' in form_data or not 'new_password' in form_data \
                or not 'password_confirmation' in form_data:
            self._errors['old_password'] = self.error_class(['Field is required'])
            self._errors['new_password'] = self.error_class(['Field is required'])
            self._errors['password_confirmation'] = self.error_class(['Field is required'])
            return form_data
        user = authenticate(username=self.instance.username, password=form_data['old_password'])
        if user is None:
            self._errors['old_password'] = self.error_class(['Wrong password'])
        if form_data['new_password'] != form_data['password_confirmation']:
            self._errors['new_password'] = self.error_class(['Passwords don\'t match'])
            self._errors['password_confirmation'] = self.error_class(['Passwords don\'t match'])
        if not re.match(r'[A-Za-z0-9@#$%^&+=]{8,32}', form_data['new_password']):
            self._errors['new_password'] = self.error_class(['Password must contain uppercase and lowercase '
                                                             'letters and has at least eight (8) characters '
                                                             'but no more than thirty two (32) characters.'])
        return form_data


class SignupUserForm(ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
        form_data = super(SignupUserForm, self).clean()
        no_required_data = False
        if not self.is_valid():
            no_required_data = True
        if User.objects.filter(username=form_data['username']):
            self._errors['username'] = self.error_class(['User with this username already exists.'])
            no_required_data = True
        if User.objects.filter(email=form_data['email']):
            self._errors['email'] = self.error_class(['User with this email already exists.'])
            no_required_data = True
        if self.cleaned_data['password'] != self.cleaned_data['password2']:
            self._errors['password'] = self.error_class(['Passwords don\'t match'])
            self._errors['password2'] = self.error_class(['Passwords don\'t match'])
            no_required_data = True
        if not re.match(r'[A-Za-z0-9@#$%^&+=]{8,32}', self.cleaned_data['password']):
            self._errors['password'] = self.error_class(['Password must contain uppercase and lowercase '
                                                          'letters and has at least eight (8) characters '
                                                          'but no more than thirty two (32) characters.'])
            no_required_data = True
        if no_required_data == True:
            return form_data


class SignupUserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone_number', 'vero_api_key']

    def __init__(self, *args, **kwargs):

        super(SignupUserProfileForm, self).__init__(*args, **kwargs)
    def __str__(self):

        return 'Profile for user {}'.format(self.user.username)

    def clean(self):
        form_data = super(SignupUserProfileForm, self).clean()
        if self.cleaned_data.get('vero_api_key', None):
            r = requests.request('POST', 'https://api.getvero.com/api/v2/users/track',
                             json={'auth_token': form_data['vero_api_key'], 'id': 'test', 'email': '',
                                   })
            if r.status_code == 401:
                self._errors['vero_api_key'] = self.error_class(['Your credentials are invalid!!!'])
                return form_data

contacts/apps/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
import json
import logging
import traceback
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseServerError, HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import FormView
from contacts.apps.accounts.forms import SettingsForm, SettingsProfileForm, ChangePasswordForm, \
    SignupUserForm, SignupUserProfileForm

from contacts.apps.accounts.models import UserProfile

logger = logging.getLogger('contacts')


class LoginPage(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('core:all_contacts'))
        return render(request, self.template_name, {'error': False})

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        logger.debug('Authenticating user %s with password: %s' % (username, password))
        if User.objects.filter(email=username):
            username = User.objects.get(email=username).username
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('core:all_contacts'))
        else:
            logger.debug('User not authenticated. Wrong login(%s)/password(%s).' % (request.POST['username'],
                                                                                    request.POST['password']))
            return render(request, self.template_name, {'error': True,
                                                        'message': 'User not authenticated. Wrong login/password'})


@method_decorator(login_required, name='dispatch')
class SettingsPage(View):
    template_name = 'settings.html'

    def get(self, request, *args, **kwargs):
        try:
            form = SettingsForm(instance=request.user)
            form_profile = SettingsProfileForm(instance=request.user.profile)
        except Exception as e:
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
        else:
            return render(request, self.template_name, {'form': form,
                                                        'form_profile': form_profile,
                                                        'updated': False})

    def post(self, request, *args, **kwargs):
        try:
            updated = False
            form = SettingsForm(request.POST, instance=request.user)
            form_profile = SettingsProfileForm(request.POST, instance=request.user.profile)
            if form.is_valid() and form_profile.is_valid():
                form.save()
                form_profile.save()
                updated = True
        except Exception as e:
            print e
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
            return HttpResponseServerError()
        else:
            return render(request, self.template_name, {'form': form,
                                                        'form_profile': form_profile,
                                                        'updated': updated})


class ChangePasswordView(View):
    template_name = 'change_password_form.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        try:
            data = {}
        except Exception as e:
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
        else:
            return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        try:
            form = ChangePasswordForm(request.POST, instance=request.user)
            if form.is_valid():
                user = request.user
                user.set_password(form.cleaned_data['new_password'])
                user.save()
                return HttpResponse(json.dumps({'success': True}),
                                    content_type='application/json')
            else:
                return HttpResponse(json.dumps({'success': False,
                                                'errors': [(k, v[0]) for k, v in form.errors.items()]}),
                                    content_type='application/json')
        except Exception as e:
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))


class RegisterFormView(FormView):
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        form = SignupUserForm()
        form_profile = SignupUserProfileForm()
        context = {'form': form,
                   'form_profile': form_profile}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        updated = False
        try:
            form = SignupUserForm(request.POST)
            form_profile = SignupUserProfileForm(request.POST)
            if form.is_valid() and form_profile.is_valid():
                # Create a new user object but avoid saving it yet
                new_user = form.save(commit=False)
                # Set the chosen password
                new_user.set_password(form.cleaned_data['password'])
                # Save the User object
                new_user.save()
                user_profile = form_profile.save(commit=False)
                user_profile.user = new_user
                user_profile.save()
                updated = True
                template_name1 = 'login.html'
                return render(request, template_name1, {'updated': updated,})
                # return HttpResponseRedirect(reverse('accounts:login'))
        except Exception as e:
            print e
            logger.error('Exception: %s. Trace: %s.' % (e, traceback.format_exc(limit=10)))
        else:
            return render(request, self.template_name, {'form': form,
                                                        'form_profile':form_profile})

contacts/apps/accounts/templates/register.html
{% extends 'base_auth.html' %}
{% load static %}
{% block title %} Contacts | Sign Up{% endblock %}
{% block body %}
    <body class="hold-transition register-page">
    <div class="register-box registration-box">
        <div class="register-logo" style="">
            <a href="/"><b>Contacts</b> Data Base</a>
        </div>
        <div class="register-box-body">
            <form id="signup_form" method="post" action="{% url "accounts:register" %}">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <p class="text-red text-center">{{ error|escape }}</p>
                {% endfor %}
                {% for error in form_profile.non_field_errors %}
                    <p class="text-red text-center">{{ error|escape }}</p>
                {% endfor %}
                <div class="form-group has-feedback {% if form.username.errors %} has-error {% endif %}">
                    <input type="text" class="form-control" id="username"
                           value="{% if form.username.value %}{{ form.username.value }}{% endif %}" name="username"
                           placeholder="Username" required>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    {% for error in form.username.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="form-group {% if form.first_name.errors %} has-error {% endif %}">
                    <input type="text" class="form-control"
                           value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                           name="first_name" placeholder="First name" required>
                    {% for error in form.first_name.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="form-group {% if form.last_name.errors %} has-error {% endif %}">
                    <input type="text" class="form-control"
                           value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" name="last_name"
                           placeholder="Last Name" required>
                    {% for error in form.last_name.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="form-group has-feedback  {% if form.email.errors %} has-error {% endif %}">
                    <input type="email" class="form-control"
                           value="{% if form.email.value %}{{ form.email.value }}{% endif %}" name="email"
                           placeholder="Email" required>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    {% for error in form.email.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="form-group  {% if form_profile.phone_number.errors %} has-error {% endif %}">
                    <input type="text" class="form-control"
                           value="{% if form_profile.phone_number.value %}{{ form_profile.phone_number.value }}{% endif %}"
                           name="phone_number" placeholder="Phone Number" required>
                    {% for error in form_profile.phone_number.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="form-group has-feedback  {% if form.password.errors %} has-error {% endif %}">
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    {% for error in form.password.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="form-group has-feedback  {% if form.password2.errors %} has-error {% endif %}">
                    <input type="password" class="form-control" name="password2" placeholder="Password Confirmation" required>
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                    {% for error in form.password2.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="form-group has-feedback {% if form_profile.vero_api_key.value %} has-error {% endif %}">
                    <input type="text" class="form-control"
                           value="{% if form_profile.vero_api_key.value %}{{ form_profile.vero_api_key.value }}{% endif %}" name="vero_api_key"
                           placeholder="Vero Token API" required>
                    {% for error in form_profile.vero_api_key.errors %}
                        <span class="help-block">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign Up</button>
                    </div>
                </div>
            </form>
            <a href="/login" class="text-center">I already have a membership</a>
        </div>
    </div>
{#    <!-- jQuery 2.1.4 -->#}
{#    <script src="{% static "plugins/jQuery/jQuery-2.1.4.min.js" %}"></script>#}
{#    <!-- Bootstrap 3.3.5 -->#}
{#    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>#}
{#    <!-- iCheck -->#}
{#    <script src="{% static "plugins/iCheck/icheck.min.js" %}"></script>#}
    <script src="{% static "js/accounts/login.js" %}"></script>
    </body>
{% endblock %}

contacts/apps/accounts/templates/settings.html
{% extends "base.html" %}
{% load staticfiles %}
{% block header %}
    <title>Settings</title>
{% endblock %}
{% block content_wrapper %}
    {% if updated %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> Done!</h4>
            Settings was updated successfully.
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-offset-3 col-md-6 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Settings
                        <small></small>
                    </h2>
                    <ul class="nav navbar-right panel_toolbox" id="float_right">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ user.first_name }} {{ user.last_name }}
                           </h3>
                    </div>


                <form class="form-horizontal" method="POST" action="{% url "accounts:settings" %}">
                        {% csrf_token %}
                        <div class="box-body">
                            <div class="form-group">
                                <label for="username" class="col-sm-3 control-label">Username</label>
                                <div class="col-sm-6 {% if form.username.errors %} has-error {% endif %}">
                                    <input name="username" type="text" class="form-control" id="username"
                                           value="{{ form.username.value }}" placeholder="Username" readonly required>
                                    <span class="help-block">{{ form.username.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="first_name" class="col-sm-3 control-label">First Name</label>

                                <div class="col-sm-6 {% if form.first_name.errors %} has-error {% endif %}">
                                    <input name="first_name" type="text" class="form-control"
                                           value="{{ form.first_name.value }}" id="first_name"
                                           placeholder="First Name" required>
                                    <span class="help-block">{{ form.first_name.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="last_name" class="col-sm-3 control-label">Last Name</label>

                                <div class="col-sm-6 {% if form.last_name.errors %} has-error {% endif %}">
                                    <input name="last_name" type="text" class="form-control"
                                           value="{{ form.last_name.value }}" id="last_name" placeholder="Last Name"
                                           required>
                                    <span class="help-block">{{ form.last_name.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-sm-3 control-label">Email</label>

                                <div class="col-sm-6 {% if form.email.errors %} has-error {% endif %}">
                                    <input name="email" type="email" class="form-control" value="{{ form.email.value }}"
                                           id="email" placeholder="Email" required>
                                    <span class="help-block">{{ form.email.errors }}</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="phone_number" class="col-sm-3 control-label">Phone Number</label>

                                <div class="col-sm-6 {% if form_profile.phone_number.errors %} has-error {% endif %}">
                                    <input name="phone_number" type="text" class="form-control"
                                           value="{{ form_profile.phone_number.value }}" id="phone_number"
                                           placeholder="Phone Number" required>
                                    <span class="help-block">{{ form_profile.phone_number.errors }}</span>
                                </div>
                            </div>
                            <!--Vero Settings-->
                            <div class="form-group">
                                <label for="vero_api_key" class="col-sm-3 control-label">API Auth Token</label>
                                <div class="col-sm-6 {% if form_profile.vero_api_key.errors %} has-error {% endif %}">
                                    <input type="text" class="form-control"
                                           name="vero_api_key"
                                           value="{{form_profile.vero_api_key.value}}" id="vero_api_key"
                                           placeholder="API Auth Token Get Vero" readonly="readonly">
                                    <span class="help-block">{{ form_profile.vero_api_key.errors }}</span>
                                </div>
                            </div>
                            <!-- Vero Settings block end -->


                            <div class="form-group">
                                <div class=" col-sm-offset-3 col-sm-6 ">
                                    <input type="button" id="change_password" class="btn btn-danger col-sm-12"
                                           value="Change Password">
                                </div>
                            </div>


                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="submit" class="btn btn-warning pull-right">Save</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>


{#                    <form class="form-horizontal" method="POST" action="{% url "accounts:settings" %}">#}
{#                        {% csrf_token %}#}
{#                        <div class="box-body">#}
{#                            <div class="form-group">#}
{#                                <label for="username" class="col-sm-3 control-label">Username</label>#}
{#                                <div class="col-sm-6 {% if form.username.errors %} has-error {% endif %}">#}
{#                                    <input name="username" type="text" class="form-control" id="username"#}
{#                                           value="{{ form.username.value }}" placeholder="Username">#}
{#                                    <span class="help-block">{{ form.username.errors }}</span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                <label for="first_name" class="col-sm-3 control-label">First Name</label>#}
{##}
{#                                <div class="col-sm-6 {% if form.first_name.errors %} has-error {% endif %}">#}
{#                                    <input name="first_name" type="text" class="form-control"#}
{#                                           value="{{ form.first_name.value }}" id="first_name" placeholder="First Name">#}
{#                                    <span class="help-block">{{ form.first_name.errors }}</span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                <label for="last_name" class="col-sm-3 control-label">Last Name</label>#}
{##}
{#                                <div class="col-sm-6 {% if form.last_name.errors %} has-error {% endif %}">#}
{#                                    <input name="last_name" type="text" class="form-control"#}
{#                                           value="{{ form.last_name.value }}" id="last_name" placeholder="Last Name">#}
{#                                    <span class="help-block">{{ form.last_name.errors }}</span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                <label for="email" class="col-sm-3 control-label">Email</label>#}
{##}
{#                                <div class="col-sm-6 {% if form.email.errors %} has-error {% endif %}">#}
{#                                    <input name="email" type="email" class="form-control" value="{{ form.email.value }}"#}
{#                                           id="email" placeholder="Email">#}
{#                                    <span class="help-block">{{ form.email.errors }}</span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                <label for="phone_number" class="col-sm-3 control-label">Phone Number</label>#}
{##}
{#                                <div class="col-sm-6 {% if form.phone_number.errors %} has-error {% endif %}">#}
{#                                    <input name="phone_number" type="text" class="form-control"#}
{#                                           value="{{ form.phone_number.value }}" id="phone_number"#}
{#                                           placeholder="Phone Number">#}
{#                                    <span class="help-block">{{ form.phone_number.errors }}</span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <!--Vero Settings-->#}
{#                            <div class="form-group">#}
{#                                <label for="vero_api_key" class="col-sm-3 control-label">API Auth Token</label>#}
{#                                <div class="col-sm-6">#}
{#                                    <input type="text" class="form-control"#}
{#                                           name="vero_api_key_readonly"#}
{#                                           value="{{ form.vero_api_key_readonly.value }}" id="vero_api_key"#}
{#                                           placeholder="API Auth Token Get Vero" readonly="readonly">#}
{#                                    <span class="help-block"></span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <!-- Vero Settings block end -->#}
{#                            <div class="form-group">#}
{#                                <div class=" col-sm-offset-3 col-sm-6 ">#}
{#                                    <input type="button" id="change_password" class="btn btn-danger col-sm-12"#}
{#                                           value="Change Password">#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <!-- /.box-body -->#}
{#                        <div class="box-footer">#}
{#                            <button type="submit" class="btn btn-warning pull-right">Save</button>#}
{#                        </div>#}
{#                        <!-- /.box-footer -->#}
{#                    </form>#}


                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js_bottom %}
    <script src="{% static "js/accounts/settings.js" %}"></script>
{% endblock %}